django_presskit/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.presskit, name='default'),
    url(r'^(?P<company_slug>[-\w]+)/$', views.presskit, name='company'),
    url(r'^projects/(?P<project_slug>[-\w]+)/$', views.project, name='project'),
    url(r'^projects/(?P<project_slug>[-\w]+)/data.xml$', views.project_xml, name='project_xml'),
    url(r'^projects/(?P<project_slug>[-\w]+)/images/header.png$', views.project_header, name='project_header'),
]

presskit/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
import django_presskit
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='presskit/')),
    path('admin/', admin.site.urls),
    url(r'^presskit/', include(('django_presskit.urls', 'django_presskit'), namespace="django_presskit")),
]

django_presskit/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from filer.fields.file import FilerFileField
from filer.fields.image import FilerImageField


class AdditionalLink(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(null=True, blank=True)
    website = models.URLField()
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['my_order', 'datetime_updated']

    def __unicode__(self):
        return self.title + ' ' + self.website

class Attachment(models.Model):
    content = models.ImageField()

    def __unicode__(self):
        return self.content.url

class Award(models.Model):
    description = models.CharField(max_length=200)
    info = models.CharField(max_length=1000, null=True, blank=True)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['my_order', 'datetime_updated']

    def __unicode__(self):
        return self.description


class Company(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    website = models.URLField(null=True, blank=True)
    header_image = models.ImageField(null=True, blank=True)#related_name='company_header_image')
    based_in = models.CharField(max_length=400, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    history = models.TextField(null=True, blank=True)
    analytics = models.CharField(max_length=200, null=True, blank=True,
                                 help_text='Your Google Analytics ID')
    founding_date = models.CharField(max_length=200, null=True,
                                     blank=True)
    press_contact = models.EmailField(
        max_length=200, null=True, blank=True,
        help_text='The primary press contact email for your company')
    phone = models.CharField(max_length=50, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    additional_links = models.ManyToManyField(AdditionalLink,
                                              blank=True)
    images = models.ManyToManyField(Attachment,
                                    through='CompanyImageAttachment',
                                    related_name='company_images')
    logos = models.ManyToManyField(Attachment,
                                   through='CompanyLogoAttachment',
                                   related_name='company_logos')
    quotes = models.ManyToManyField('Quote', blank=True)
    awards = models.ManyToManyField('Award', blank=True)
    credits = models.ManyToManyField('Credit', blank=True)
    contacts = models.ManyToManyField('Contact', blank=True)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    asset_archive = models.FileField(blank=True,null=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('django_presskit:company', kwargs={'company_slug': self.slug})

    class Meta:
        verbose_name_plural = 'companies'


class CompanyImageAttachment(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    attachment = models.ForeignKey(Attachment,
                                   on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['my_order', 'datetime_updated']


class CompanyLogoAttachment(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    attachment = models.ForeignKey(Attachment,
                                   on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['my_order', 'datetime_updated']


class CompanyVideo(models.Model):
    name = models.CharField(max_length=400)
    company = models.ForeignKey(Company, related_name='videos', on_delete=models.CASCADE)
    embed_url = models.URLField(null=True, blank=True)
    file = models.FileField(null=True, blank=True)#,related_name='company_video')
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['my_order', 'datetime_updated']


class Contact(models.Model):
    name = models.CharField(max_length=300)
    website = models.URLField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['my_order', 'datetime_updated']

    def __unicode__(self):
        return self.name


class Credit(models.Model):
    person = models.CharField(max_length=300)
    website = models.URLField(null=True, blank=True)
    role = models.TextField(null=True, blank=True)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['my_order', 'datetime_updated']

    def __unicode__(self):
        return self.person + ', ' + self.role


class Feature(models.Model):
    description = models.CharField(max_length=1000)
    project = models.ForeignKey('Project', on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['my_order', 'datetime_updated']

    def __unicode__(self):
        return self.description


class MonetizationPermission(models.Model):
    option = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.option


class Platform(models.Model):
    name = models.CharField(max_length=200)
    website = models.URLField(null=True, blank=True)
    project = models.ForeignKey('Project', on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['my_order', 'datetime_updated']

    def __unicode__(self):
        return self.project.title + ' - ' + self.name


class Price(models.Model):
    price = models.CharField(max_length=200)
    project = models.ForeignKey('Project', on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['my_order', 'datetime_updated']

    def __unicode__(self):
        return self.project.title + ' - ' + self.price


class Project(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    header_image = models.ImageField(null=True, blank=True)#,related_name='project_header_image')
    release_date = models.CharField(max_length=200)
    website = models.URLField()
    description = models.TextField()
    history = models.TextField()
    images = models.ManyToManyField(Attachment,
                                    through='ProjectImageAttachment',
                                    related_name='project_images')
    logos = models.ManyToManyField(Attachment,
                                   through='ProjectLogoAttachment',
                                   related_name='project_logos')
    press_can_request_copy = models.BooleanField()
    monetization_permission = models.ForeignKey(MonetizationPermission, on_delete=models.CASCADE)
    distribute_game_id = models.CharField(
        null=True, blank=True, max_length=25, help_text='The game ID from your Distribute() keyfile (https://dodistribute.com/games/presskit/THIS-ID/)')
    distribute_access_hash = models.CharField(
        null=True, blank=True, max_length=25, help_text='The access hash from your Distribute() keyfile (https://dodistribute.com/access/add/THIS-HASH/)')
    distribute_key = models.CharField(
        null=True, blank=True, max_length=80, help_text='The key from your Distribute() keyfile filename (ds_THIS-KEY)')
    quotes = models.ManyToManyField('Quote', blank=True)
    additional_links = models.ManyToManyField(AdditionalLink,
                                              blank=True)
    awards = models.ManyToManyField('Award', blank=True)
    credits = models.ManyToManyField(Credit, blank=True)
    contacts = models.ManyToManyField(Contact, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_updated = models.DateTimeField(auto_now=True)

django_presskit/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import zipfile
import os
from io import BytesIO

from django.conf import settings
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.views.decorators.cache import cache_page

from .models import Company, Project

def fallback(func):
  def decorator(*args, **kwargs):
    try:
      return func(*args, **kwargs)
    except (Company.DoesNotExist, Project.DoesNotExist) as e:
      return redirect('django_presskit:default')

  return decorator

@fallback
def presskit(request, company_slug=None):
    if not company_slug:
      try:
        company = Company.objects.get(pk=settings.DJANGO_PRESSKIT_DEFAULT_COMPANY_ID)
      except Exception as e:
        return render(request, 'django_presskit/no_default.html')
    else:
      company = Company.objects.get(slug=company_slug)
    context = {
      'request': request,
      'company': company,
    }
    return render(request, 'django_presskit/company.html', context)

@fallback
def project(request, project_slug):
    project = Project.objects.get(slug=project_slug)
    context = {
      'request': request,
      'project': project,
    }
    return render(request, 'django_presskit/project.html', context)

def project_xml(request, project_slug):
    project = Project.objects.get(slug=project_slug)
    context = {
      'project': project,
    }
    return render(request, 'django_presskit/data.xml', context, content_type='text/xml')

def project_header(request, project_slug):
    project = Project.objects.get(slug=project_slug)
    if project.header_image:
      return redirect(project.header_image.url, permanent=True)
    else:
      raise Http404("No header image for this project.")

django_presskit/templates/django_presskit/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta content="text/html; charset=UTF-8" name="Content-Type" />
  <link rel="stylesheet" href="{% static "django_presskit/django_presskit.css" %}"/>
  <title>{% block title %}Django Presskit{% endblock %}</title>

  {% block extra-head %}{% endblock %}
</head>

<body>
  <header class="page-header">
    {% block header %}{% endblock %}
  </header>

  <div class="identity">
    {% block identity %}{% endblock %}
  </div>

  <div class="above-fold">
    {% block above-fold %}{% endblock %}
  </div>
  <section class="factsheet" id="factsheet">
    {% block factsheet %}{% endblock %}
  </section>
  <div class="below-fold">
    {% block below-fold %}{% endblock %}
  </div>

  <nav class="navigation">
    {% block navigation %}
    {% endblock %}
  </nav>

  <footer class="page-footer">
    {% block footer %}
    <p>
      Django Presskit by <a href="https://futureproofgames.com">Future Proof Games</a> •
      Inspired by Rami Ismail's <a href="http://dopresskit.com/">presskit()</a>
    </p>
    {% endblock %}
  </footer>

  {% block pageend %}
  {% endblock %}
</body>
</html>

django_presskit/templates/django_presskit/navitem.html
{% if item %}
  <li><a href="#{{anchor}}">{{title}}</a></li>
{% endif %}

django_presskit/templates/django_presskit/no_default.html
<html>
<body>
  <h1>No Default Company Set</h1>
  <p>To choose a default company, set <code>DJANGO_PRESSKIT_DEFAULT_COMPANY_ID</code> in your settings file.</p>
</body>
</html>

django_presskit/templates/django_presskit/project.html
{% extends "django_presskit/base.html" %}
{% load dpk_util thumbnail %}

{% block extra-head %}
{% condense %}
<meta property="og:title" content="{{product.title}}">
<meta property="og:description" content="{{product.description | markdown | striptags}}">
{% if product.header_image %}
  <meta property="og:image" content="{{ product.header_image.url }}">
{% endif %}

{% if product.logos.count %}
  {% for image in product.logos.all %}
    <meta property="og:image" content="{{image.content.url}}">
  {% endfor %}
{% endif %}

{% if product.images.count %}
  {% for image in product.images.all %}
    <meta property="og:image" content="{{image.content.url}}">
  {% endfor %}
{% endif %}

<meta property="og:url" content="{{request.build_absolute_uri}}">

{% if product.videos.count %}
  {% for video in product.videos.all %}
    <meta property="og:video" content="{% firstof video.file.url video.embed_url %}">
  {% endfor %}
{% endif %}

<meta name="twitter:card" content="summary">

<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "CreativeWork",
  "additionalType": "Product",
  "name": "{{project.title}}",
  "description": "{{project.description | markdown | striptags}}",

  {% if project.website %}
    "url": "{{project.website | with_protocol}}",
  {% endif %}

  "author": {
    "@type": "Organization",
    {% if project.company.website %}
      "url": "{{project.company.website | with_protocol}}",
    {% endif %}
    "name": "{{project.company.title}}"
  },

  {% if project.feature_set.count %}
    "additionalProperty": [
      {% for feature in project.feature_set.all %}
        {
          "description": "{{feature.description | markdown | striptags}}",
          "@type": "PropertyValue"
        }{% if not forloop.last %},{% endif %}
      {% endfor %}
    ],
  {% endif %}

  {% if project.price_set.count %}
    "offer": [
      {% for price in project.price_set.all %}
        {
          "description": "{{price.price}}",
          "@type": "Offer"
        }{% if not forloop.last %},{% endif %}
      {% endfor %}
    ],
  {% endif %}

  {% if project.videos.count %}
    "video": [
      {% for video in project.videos.all %}
        {
          "name": "{{video.name}}",
          {% if video.file %}"contentUrl": "{{video.file.url}}",{% endif %}
          {% if video.embed_url %}"embedUrl": "{{video.embed_url}}",{% endif %}
          "@type": "VideoObject"
        }{% if not forloop.last %},{% endif %}
      {% endfor %}
    ],
  {% endif %}

  {% if project.images.count %}
    "image": [
      {% for image in project.images.all %}
        "{{image.content.url}}"{% if not forloop.last %},{% endif %}
      {% endfor %}
    ],
  {% endif %}

  {% if project.logos.count %}
    "logo": [
      {% for logo in project.logos.all %}
        "{{logo.content.url}}"{% if not forloop.last %},{% endif %}
      {% endfor %}
    ],
  {% endif %}

  {% if project.quotes.count %}
    "review": [
      {% for quote in project.quotes.all %}
        {
          "description": "{{quote.description | markdown | striptags}}",
          "url": "{{quote.website | with_protocol}}",
          "author": {
            "name": "{{quote.reviewer}}",
            "@type": "Person"
          },
          "publisher": {
            "name": "{{quote.publication_name}}",
            "@type": "Organization"
          },
          "@type": "Review"
        }{% if not forloop.last %},{% endif %}
      {% endfor %}
    ],
  {% endif %}

  {% if project.additional_links.count %}
    "subjectOf": [
      {% for link in project.additional_links.all %}
        {
          "name": "{{link.title}}",
          "description": "{{link.description}}",
          "url": "{{link.website | with_protocol}}",
          "@type": "WebPage"
        }{% if not forloop.last %},{% endif %}
      {% endfor %}
    ],
  {% endif %}

  {% if project.credits.count %}
    "contributor": [
      {% for credit in project.credits.all %}
        {
          "name": "{{credit.person}}",
          {% if credit.website %}
            "url": "{{credit.website | with_protocol}}",
          {% endif %}
          "@type": "Person"
        }{% if not forloop.last %},{% endif %}
      {% endfor %}
    ],
  {% endif %}

  "@id": "{{request.build_absolute_uri}}"
}
{% endcondense %}
</script>
{% endblock %}

{% block title %}{{project.title}} Presskit{% endblock %}

{% block identity %}
<a href="{% url 'django_presskit:default' %}" class="identity-link"><h1>{{project.company.title}} Presskit</h1></a>
{% endblock %}

{% block header %}
<h1>
{% if project.header_image %}
  <img class="header-image" src="{{ project.header_image.url }}" alt="{{project.title}}">
{% else %}
  {{project.title}}
{% endif %}
</h1>
{% endblock %}{# header #}

{% block above-fold %}
{% if project.description %}
  <section id="description">
    <h2>Description</h2>

    {{project.description | markdown}}
  </section>
{% endif %}

{% if project.history %}
  <section id="history">
    <h2>History</h2>

    {{project.history | markdown}}
  </section>
{% endif %}

{% if project.feature_set.count %}
  <section id="features">
    <h2>Features</h2>

    <ul class="feature-list">
      {% for feature in project.feature_set.all %}
        <li>{{feature.description | markdown}}</li>
      {% endfor %}
    </ul>
  </section>
{% endif %}

{% endblock %}{# above-fold #}

{% block factsheet %}
<h2>Factsheet</h2>

<h3>{{project.title}}</h3>

<section>
  <h3>Developer:</h3>
  <p>
    {% if project.company.website %}
      <a href="{{project.company.website | with_protocol}}">{{project.company.title}}</a>
    {% else %}
      {{project.company.title}}
    {% endif%}
    {% if project.company.based_in %}<br>Based in {{project.company.based_in}}{% endif %}
  </p>
</section>

{% if project.release_date %}
<section>
  <h3>Release Date:</h3>
  <p>{{project.release_date}}</p>
</section>
{% endif %}

{% if project.platform_set.count %}
<section>
  <h3>Platforms:</h3>
  <ul>
  {% for platform in project.platform_set.all %}
    <li><a href="{{ platform.website }}">{{platform.name}}</a></li>
  {% endfor %}
  </ul>
</section>
{% endif %}

{% if project.website %}
<section>
  <h3>Website:</h3>
  <p><a href="{{project.website}}">{{project.website}}</a></p>
</section>
{% endif %}

{% if project.price_set.count %}
<section>
  <h3>Regular Price:</h3>
  <ul>
  {% for price in project.price_set.all %}
    <li>{{price.price}}</li>
  {% endfor %}
  </ul>
</section>
{% endif %}

{% endblock %}{# factsheet #}

{% block below-fold %}
{% if project.videos.count %}
  <section id="videos">
    <h2>Videos</h2>
    <ul>
    {% for video in project.videos.all %}
      <li>
        <h3>{{ video.name }}</h3>
        {% if video.file %}(<a href="{{video.file.url}}" download>Download</a>){% endif %}
        {% if video.embed_url %}
          <div class="video-responsive">
            <iframe src="{{ video.embed_url }}"></iframe>
          </div>
        {% endif%}
    {% endfor %}
    </ul>
  </section>
{% endif %}

{% if project.images.count %}
  <section id="images">
    <h2>Images</h2>
    {% for image in project.images.all %}
      <a href="{{ image.content.url }}"><img class="attached-image" src="{% thumbnail image.content 250x250 crop %}"></a>
    {% endfor %}
    {% if project.asset_archive %}
      <p><a href="{{project.asset_archive.url}}" download>Download Archive</a></p>
    {% endif %}
  </section>
{% endif %}

{% if project.logos.count %}
  <section id="logos">
    <h2>Logo &amp; Icon</h2>
    {% for image in project.logos.all %}
      <a href="{{ image.content.url }}"><img class="attached-image" src="{% thumbnail image.content 250x250 crop %}"></a>
    {% endfor %}
  </section>
{% endif %}

{% if project.awards.count %}
  <section id="awards">
    <h2>Awards &amp; Recognition</h2>
    <ul>
    {% for award in project.awards.all %}
      <li>{{award.description}} {% if award.info %}<cite>{{award.info}}</cite>{% endif %}</li>
    {% endfor %}
    </ul>
  </section>
{% endif %}

{% if project.quotes.count %}
  <section id="quotes">
    <h2>Selected Articles</h2>
    {% for quote in project.quotes.all %}
      <blockquote class="quotation quotation--project">
        {{quote.description | markdown}}
        <cite>
          <a href="{{quote.website | with_protocol}}">
            {{quote.reviewer}},
            <span class='quotation__publication'>{{quote.publication_name}}</span>
          </a>
        </cite>
      </blockquote>
    {% endfor %}
  </section>
{% endif %}

{% if project.distribute_key and project.distribute_access_hash %}
  <section id="request">
    <h2>Request Press Copy</h2>
    <p>Please fill in your e-mail address below to complete a distribute() request and we'll get back to you as soon as a press copy is available for you.</p>
    <form id="pressrequest" method="post" action="https://dodistribute.com/access/add/{{project.distribute_access_hash}}/">
      <input type="email" id="email" name="email" placeholder="name@yourdomain.com"></input>
      <input type="hidden" id="key" name="key" value="{{project.distribute_key}}"></input>
      <input type="submit" id="submit-button" value="Request a press copy"></input>
    </form>
    <p>Alternatively, you can always request a press copy by <a href="#contact">sending us a quick email</a>.</p>
  </section>
{% endif %}

{% if project.additional_links.count %}
  <section id="additional-links">
    <h2>Additional Links</h2>
    {% for link in project.additional_links.all %}
      <h3 class="additional-links">{{link.title}}</h3>

      <p>{{link.description}} <a href="{{link.website | with_protocol}}">{{link.website | domain}}</a></p>
    {% endfor %}
  </section>
{% endif %}

<div class="bottom-columns">

{% if project.credits.count %}
<section id="team">
  <h2>{{project.title}} Credits</h2>
  {% for credit in project.credits.all %}
    <section class="credit">
      <h3>{{credit.person}}</h3>
      {% if credit.website or credit.role %}
        {% if credit.website %}<a href="{{credit.website | with_protocol}}">{% endif %}
          {{ credit.role|default:"Website" }}
        {% if credit.website %}</a>{% endif %}
      {% endif %}
    </section>
  {% endfor %}
</section>
{% endif %}

{% if project.contacts.count %}
<section id="contact">
  <h2>Contact</h2>
  {% for contact in project.contacts.all %}
    <h3>{{contact.name}}</h3>

    {% if contact.website %}
      <p><a href="{{contact.website | with_protocol}}">{{contact.website}}</a></p>
    {% endif %}

    {% if contact.email %}
      <p><a href="{{contact.email | with_protocol}}">{{contact.email}}</a></p>
    {% endif %}
  {% endfor %}
</section>
{% endif %}

</div>

{% endblock %}{# below-fold #}

{% block navigation %}
<ul class="main-navigation">
  {% optional_navitem project 'factsheet' 'Factsheet' %}
  {% optional_navitem project.description 'description' 'Description' %}
  {% optional_navitem project.history 'history' 'History' %}
  {% optional_navitem project.feature_set.count 'features' 'Features' %}
  {% optional_navitem project.project_set.count 'projects' 'Projects' %}
  {% optional_navitem project.videos.count 'videos' 'Videos' %}
  {% optional_navitem project.images.count 'images' 'Images' %}
  {% optional_navitem project.logos.count 'logos' 'Logo &amp; Icon' %}
  {% optional_navitem project.awards.count 'awards' 'Awards &amp; Recognition' %}
  {% optional_navitem project.quotes.count 'quotes' 'Selected Articles' %}
  {% optional_navitem project.distribute_access_hash 'request' 'Request Press Copy' %}
  {% optional_navitem project.additional_links.count 'additional-links' 'Additional Links' %}
  {% optional_navitem project.credits.count 'team' 'Team' %}
  {% optional_navitem project 'contact' 'Contact' %}
</ul>
{% endblock %}{# navigation #}

{% block pageend %}
{% if project.analytics %}
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '{{project.analytics}}']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
{% endif %}
{% endblock %}